name: ContinuousIntegration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_matrix:
    strategy:
      matrix:
        BUILD_TYPE: [Debug, Release]
        os: [ubuntu-latest, macos-latest, windows-latest]

    timeout-minutes: 10
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}} -j 3

      - name: Test
        run: ctest --test-dir ${{github.workspace}}/build -C ${{matrix.BUILD_TYPE}} --verbose

